# Generated by Django 5.0.4 on 2024-05-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urunismi', models.CharField(max_length=100)),
                ('aciklama', models.TextField(max_length=100)),
                ('fiyat', models.IntegerField(default=0)),
            ],
        ),
    ]
