# Generated by Django 5.0.4 on 2024-05-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='urunResmi'),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='aciklama',
            field=models.TextField(max_length=100, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='fiyat',
            field=models.IntegerField(default=0, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='urunismi',
            field=models.CharField(max_length=100, verbose_name='Ürün İsmi'),
        ),
    ]
